Fixing command bug from backend docker

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -8,7 +8,7 @@ RUN apt-get update --fix-missing && \
     apt-get install -y --no-install-recommends -f \
     wget curl unzip gnupg \
     libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 \
-    libxkbcommon0 libxrandr2 xdg-utils libglib2.0-0 libnss3 libgconf-2-4 \
+    libxkbcommon0 libxrandr2 xdg-utils libglib2.0-0 libnss3 \
     libx11-xcb1 libxcursor1 libxi6 libxrender1 libdbus-glib-1-2 libgtk-3-0 && \
     rm -rf /var/lib/apt/lists/*
 
@@ -26,8 +26,8 @@ RUN set -eux; \
     echo "ChromeDriver LATEST_RELEASE Version: ${CHROME_DRIVER_VERSION}"; \
     wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.53/linux64/chromedriver-linux64.zip"; \
     if [ ! -s /tmp/chromedriver.zip ]; then \
-        echo "ERROR: ChromeDriver zip file download failed or resulted in empty file!"; \
-        exit 1; \
+    echo "ERROR: ChromeDriver zip file download failed or resulted in empty file!"; \
+    exit 1; \
     fi; \
     unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
     mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver && \
